"""
Pydantic models for the Doctor's Intelligent Assistant.

These models define the data structures that flow through our LangGraph state machine.
"""

from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field
from datetime import datetime


class PatientIntakeInput(BaseModel):
    """Raw patient intake data from the form or conversation."""

    patient_id: str = Field(..., description="Unique patient identifier")
    raw_input: str = Field(..., description="Raw conversational patient intake text")
    session_id: Optional[str] = Field(None, description="Session ID for multi-turn conversations")
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class StructuredPatientData(BaseModel):
    """Structured patient data extracted by the intake agent."""

    patient_id: str
    chief_complaint: str = Field(..., description="Primary reason for visit")
    symptoms: List[str] = Field(default_factory=list, description="List of reported symptoms")
    duration: Optional[str] = Field(None, description="How long symptoms have been present")
    severity: Optional[str] = Field(None, description="Severity level (mild/moderate/severe)")
    medical_history: List[str] = Field(default_factory=list, description="Relevant medical history")
    medications: List[str] = Field(default_factory=list, description="Current medications")
    allergies: List[str] = Field(default_factory=list, description="Known allergies")
    vital_signs: Optional[Dict[str, Any]] = Field(None, description="Vital signs if available")


class ClinicalSummary(BaseModel):
    """Clinical summary generated by the summary agent."""

    concise_summary: str = Field(..., description="Brief clinical summary")
    key_findings: List[str] = Field(default_factory=list, description="Important clinical findings")
    risk_factors: List[str] = Field(default_factory=list, description="Identified risk factors")
    suggested_focus_areas: List[str] = Field(default_factory=list, description="Areas requiring attention")


class KnowledgeContext(BaseModel):
    """Relevant medical knowledge retrieved from vector database."""

    relevant_conditions: List[str] = Field(default_factory=list, description="Possible conditions")
    clinical_guidelines: List[str] = Field(default_factory=list, description="Relevant guidelines")
    similar_cases: List[Dict[str, Any]] = Field(default_factory=list, description="Similar patient cases")
    confidence_score: float = Field(default=0.0, description="Confidence in retrieval")


class SOAPReport(BaseModel):
    """Final SOAP format clinical report."""

    report_type: str = Field(default="SOAP", description="Report format type")
    patient_id: str
    generated_at: datetime = Field(default_factory=datetime.utcnow)

    # SOAP Components
    subjective: str = Field(..., description="Subjective findings (patient's report)")
    objective: str = Field(..., description="Objective findings (measurable data)")
    assessment: str = Field(..., description="Clinical assessment and diagnosis")
    plan: str = Field(..., description="Treatment plan and next steps")

    # Metadata
    confidence_level: Optional[str] = Field(None, description="Overall confidence (low/medium/high)")
    flags: List[str] = Field(default_factory=list, description="Important flags or alerts")


class GraphState(BaseModel):
    """
    The state object that flows through the LangGraph.

    This is the shared memory between all agents. Each agent reads from
    and writes to this state as the graph executes.

    Phase 4: Enhanced with routing metadata for dynamic orchestration
    Phase 5: Added patient history from memory agent
    """

    # Input
    patient_intake: Optional[PatientIntakeInput] = None

    # Agent outputs
    structured_data: Optional[StructuredPatientData] = None
    clinical_summary: Optional[ClinicalSummary] = None
    knowledge_context: Optional[KnowledgeContext] = None
    soap_report: Optional[SOAPReport] = None

    # Phase 5: Patient history from memory agent
    patient_history: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Patient's historical visits retrieved by memory agent"
    )

    # Metadata
    current_step: str = Field(default="intake", description="Current processing step")
    errors: List[str] = Field(default_factory=list, description="Any errors encountered")

    # Phase 4: Dynamic routing metadata
    case_priority: str = Field(default="routine", description="Case priority: routine, urgent, or emergency")
    routing_path: List[str] = Field(default_factory=list, description="Track which nodes were executed")
    requires_enhanced_analysis: bool = Field(default=False, description="Flag for cases needing deeper analysis")
    processing_time_ms: float = Field(default=0.0, description="Total processing time in milliseconds")

    class Config:
        arbitrary_types_allowed = True


class APIResponse(BaseModel):
    """Standard API response format."""

    success: bool
    message: str
    data: Optional[Dict[str, Any]] = None
    errors: List[str] = Field(default_factory=list)
